sudo: no

language: python

env:
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=py27-1.7
  - TOXENV=py27-1.8
  - TOXENV=py27-1.9
  - TOXENV=py27-main
  - TOXENV=py32-1.7
  - TOXENV=py32-1.8
  - TOXENV=py33-1.7
  - TOXENV=py33-1.8
  - TOXENV=py34-1.7
  - TOXENV=py34-1.8
  - TOXENV=py34-1.9
  - TOXENV=py34-main

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-1.8
    - python: 3.5
      env: TOXENV=py35-1.9
    - python: 3.5
      env: TOXENV=py35-main
  allow_failures:
    - env: TOXENV=py27-main
    - env: TOXENV=py34-main
    - env: TOXENV=py35-main

install:
  - pip install tox "virtualenv<14.0"

script:
  - tox
